apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-cluster-demo

resources:
  - cluster-deployment.yaml

configMapGenerator:
  - name: cluster-config
    files:
      - cluster-config.yaml

labels:
  - pairs:
      environment: development
      company: Red Hat
      requested-by: yoza@redhat.com
