# Cluster Configuration for test-cluster-demo-01
clusterName: test-cluster-demo-01
environment: development
cloudProvider: aws
region: us-east-1
baseDomain: openshiftpartnerlabs.com
openshiftVersion: img4.20.10-x86-64-appsub

controlPlane:
  instanceType: m5.xlarge
  replicas: 3

workers:
  instanceType: m5.2xlarge
  replicas: 2
  zones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

networking:
  clusterNetworkCIDR: 10.128.0.0/14
  serviceNetworkCIDR: 172.30.0.0/16
  machineNetworkCIDR: 10.0.0.0/16

metadata:
  companyName: Red Hat
  requestedBy: yoza@redhat.com
